/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Id = 4;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int ADD_OP = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MUL_OP = 10;
  /** RegularExpression Id. */
  int DIV_OP = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int IF_TOK = 13;
  /** RegularExpression Id. */
  int ELSE_TOK = 14;
  /** RegularExpression Id. */
  int GREQ = 15;
  /** RegularExpression Id. */
  int LSEQ = 16;
  /** RegularExpression Id. */
  int NEQ = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int EL = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<Id>",
    "<Num>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"?\"",
    "\":\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"\\n\"",
  };

}
